/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2017-01-02 03:58:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Spring MVC Tutorial</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.9.1.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("\tbackground-color: #EEEEEE;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document)\r\n");
      out.write("\t\t\t.ready(\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t/* ajax for get json */\r\n");
      out.write("\t\t\t\t\t\t$('#btnGetJson').click(function() {\r\n");
      out.write("\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\ttype : \"GET\",\r\n");
      out.write("\t\t\t\t\t\t\t\turl : \"getJson\",\r\n");
      out.write("\t\t\t\t\t\t\t\tsuccess : function(rs) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tconsole.log(rs);\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t$('#btnRole').click(function() {\r\n");
      out.write("\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\ttype : \"GET\",\r\n");
      out.write("\t\t\t\t\t\t\t\turl : \"getjson\",\r\n");
      out.write("\t\t\t\t\t\t\t\tsuccess : function(rs) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tconsole.log(rs);\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t/* ajax for post json */\r\n");
      out.write("\t\t\t\t\t\t$('#btnPostJson').click(\r\n");
      out.write("\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar person = {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"name\" : 'NhutNguyen',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"age\" : '27',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"city\" : \"HCM\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\turl : \"postjson\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata : JSON.stringify(person),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tbeforeSend : function(xhr) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\txhr.setRequestHeader(\"Accept\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"application/json\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\txhr.setRequestHeader(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"Content-Type\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"application/json\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsuccess : function(rs) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tconsole.log(rs);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t/* ajax for post file with formData */\r\n");
      out.write("\t\t\t\t\t\tvar files;\r\n");
      out.write("\t\t\t\t\t\t$(\"#myFile\").on('change', prepareLoad);\r\n");
      out.write("\t\t\t\t\t\tfunction prepareLoad(event) {\r\n");
      out.write("\t\t\t\t\t\t\tfiles = event.target.files;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t$('#subbutton').click(function() {\r\n");
      out.write("\t\t\t\t\t\t\tprocessFileUpLoad();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tfunction processFileUpLoad() {\r\n");
      out.write("\t\t\t\t\t\t\tvar strName = $('#txtFileName').val();\r\n");
      out.write("\t\t\t\t\t\t\tvar myForm = new FormData();\r\n");
      out.write("\t\t\t\t\t\t\tmyForm.append(\"file\", file[0]);\r\n");
      out.write("\t\t\t\t\t\t\tmyForm.append(\"fileName\", strName);\r\n");
      out.write("\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\turl : \"upload-file-with-ajax\",\r\n");
      out.write("\t\t\t\t\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\t\t\t\t\tdata : myForm,\r\n");
      out.write("\t\t\t\t\t\t\t\tenctype : 'multipart/form-data',\r\n");
      out.write("\t\t\t\t\t\t\t\tprocessData : false,\r\n");
      out.write("\t\t\t\t\t\t\t\tcontentType : false,\r\n");
      out.write("\t\t\t\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tconsole.log(result);\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t/* registration return token */\r\n");
      out.write("\t\t\t\t\t\t$('#registration')\r\n");
      out.write("\t\t\t\t\t\t\t\t.click(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar json = {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"userName \" : $('#txtUserName')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t.val(),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"password \" : $('#txtPassword')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t.val(),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"email\" : $('txtEmail').val()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\turl : \"user/registration\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata : JSon\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.stringify(json),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tbeforeSend : function(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\txhr) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcosole\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.log(\"heheeee\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\txhr\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.setRequestHeader(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"Accept\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"application/json\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\txhr\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.setRequestHeader(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"Content-Type\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"application/json\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tsuccess : function(res) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tif (res.data == true) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdocument\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.getElementById(\"alert\").innerHTML = \"Registration was successfully\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdocument\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.getElementById(\"alert\").innerHTML = res.message;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div style=\"text-align: center\">\r\n");
      out.write("\t\t<h2>Hey guy. This is index page</h2>\r\n");
      out.write("\t\t<a href=\"Welcome\">Click here to see welcome page</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- demo form json -->\r\n");
      out.write("\t<button id=\"btnGetJson\">Get JSon</button>\r\n");
      out.write("\t</br/>\r\n");
      out.write("\r\n");
      out.write("\t<!-- demo form post Json -->\r\n");
      out.write("\t<button id=\"btnPostJson\">Post Json</button>\r\n");
      out.write("\t<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Singer file upload no ajax -->\r\n");
      out.write("\t<h1>Single File Upload No Ajax</h1>\r\n");
      out.write("\t<form method=\"POST\" enctype=\"multipart/form-data\"\r\n");
      out.write("\t\taction=\"upload-file-no-ajax\">\r\n");
      out.write("\t\tUpload File :<input type=\"file\" name=\"myfile\"><br>\r\n");
      out.write("\t\tDesciption:<input type=\"text\" name=\"myFileName\" /> <input\r\n");
      out.write("\t\t\ttype=\"submit\" value=\"send\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<br />\r\n");
      out.write("\r\n");
      out.write("\t<!-- Singer File Upload with Ajax -->\r\n");
      out.write("\t<h1>Singer File upload Ajax</h1>\r\n");
      out.write("\tUpload File:\r\n");
      out.write("\t<input type=\"file\" id \"myFile\"/>\r\n");
      out.write("\t<br /> Description:\r\n");
      out.write("\t<input type=\"text\" ip=\"txtFileName\" />\r\n");
      out.write("\t<input type=\"button\" id \"subbutton value=\"Send\" />\r\n");
      out.write("\r\n");
      out.write("\t<!-- Registration  -->\r\n");
      out.write("\t<h1>Resgistration Token</h1>\r\n");
      out.write("\tUser Name :\r\n");
      out.write("\t<input type=\"text\"\r\n");
      out.write("\t\tid=\"txtUserName/><br/>\r\n");
      out.write("\tEmail: <input type =\"text\" id=\"txtEmail\"/><br/>\r\n");
      out.write("\tPassword : <input type=\"password\" id \" txtPassword\"/>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<input id=\"alert\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<h1>Hibernate</h1>\r\n");
      out.write("\t<button id=\"btnRole\">Read Role</button>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
